/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package mcqexamination;

import javax.swing.JOptionPane;
import dbNibriti.databaseNibriti;

/**
 *
 * @author Nibriti Poudel
 */
public class AddStudent extends javax.swing.JFrame {

    /** Creates new form AddStudent */
    public AddStudent() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTokenid = new javax.swing.JTextField();
        txtStudentname = new javax.swing.JTextField();
        txtStudentpassword = new javax.swing.JPasswordField();
        btnGeneratetoken = new javax.swing.JButton();
        btnAdmindash = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Student Fullname:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Student Password:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Token ID:");

        txtTokenid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTokenid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTokenidActionPerformed(evt);
            }
        });

        txtStudentname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtStudentpassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnGeneratetoken.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnGeneratetoken.setText("Generate Token");
        btnGeneratetoken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneratetokenActionPerformed(evt);
            }
        });

        btnAdmindash.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAdmindash.setText("Admin Dashboard");
        btnAdmindash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdmindashActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGeneratetoken, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdmindash, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTokenid, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                                .addComponent(txtStudentpassword))
                            .addComponent(txtStudentname, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(142, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtStudentname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtTokenid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtStudentpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdmindash, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGeneratetoken, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTokenidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTokenidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTokenidActionPerformed

    private void btnGeneratetokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneratetokenActionPerformed
        String token=txtTokenid.getText();
        String studentname=txtStudentname.getText();
        String password=String.valueOf(txtStudentpassword.getPassword());
        String empty = "";
        
        //For validating
        if(token.equals(empty)){
            JOptionPane.showMessageDialog(this, "Please provide a token id.");
        }
        else if(password.equals(empty)){
            JOptionPane.showMessageDialog(this, "Please provide a password.");
        }
        else{
            try {
                databaseNibriti db= new databaseNibriti();
                int result=db.addnewToken(token,password,studentname);
                if(result>0)
                {
                    JOptionPane.showMessageDialog(null,"A new token has been generated"); 
                    //To clear all the text boxes
                   txtTokenid.setText("");
                   txtStudentname.setText("");
                   txtStudentpassword.setText("");
                }
                else
                {
                    JOptionPane.showMessageDialog(null,"Unable to add Token");
                    //To clear all the text boxes
                    txtTokenid.setText("");
                   txtStudentname.setText("");
                   txtStudentpassword.setText("");
                }
          
             
             
             
         }
        
         catch (Exception ex) {
         
         }
        
        }
    }//GEN-LAST:event_btnGeneratetokenActionPerformed

    private void btnAdmindashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdmindashActionPerformed
                       //To display admin dashboard
                       AdminDash ad= new AdminDash();
                       ad.setVisible(true);
                       this.dispose();
                       ad.setResizable(false);
    }//GEN-LAST:event_btnAdmindashActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmindash;
    private javax.swing.JButton btnGeneratetoken;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtStudentname;
    private javax.swing.JPasswordField txtStudentpassword;
    private javax.swing.JTextField txtTokenid;
    // End of variables declaration//GEN-END:variables

}
