/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mcqexamination;

import java.sql.ResultSet;
import javax.swing.JOptionPane;
import dbNibriti.databaseNibriti;
import java.sql.PreparedStatement;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author Nibriti Poudel
 */
public class MyLogin extends javax.swing.JFrame {
    String uname;
    /**
     * Creates new form MyLogin
     */
    public MyLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        txtUsername = new javax.swing.JTextField();
        rbnAdmin = new javax.swing.JRadioButton();
        rbnStudent = new javax.swing.JRadioButton();
        btnLogin = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("Please Login to your account");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel2.setText("Your Password:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setText("Your Username:");

        txtPassword.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        txtUsername.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N

        rbnAdmin.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        rbnAdmin.setText("Admin");
        rbnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnAdminActionPerformed(evt);
            }
        });

        rbnStudent.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        rbnStudent.setText("Student");
        rbnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbnStudentActionPerformed(evt);
            }
        });

        btnLogin.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Note: If you're student, Username is your token id");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(30, 30, 30)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(74, 74, 74)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(142, 142, 142)
                            .addComponent(rbnAdmin)
                            .addGap(128, 128, 128)
                            .addComponent(rbnStudent)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(btnLogin)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbnAdmin)
                    .addComponent(rbnStudent))
                .addGap(31, 31, 31)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addComponent(btnLogin)
                .addGap(23, 23, 23))
        );

        txtPassword.getAccessibleContext().setAccessibleName("");
        txtUsername.getAccessibleContext().setAccessibleName("");
        rbnAdmin.getAccessibleContext().setAccessibleName("");
        rbnStudent.getAccessibleContext().setAccessibleName("");
        btnLogin.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnStudentActionPerformed
        
    }//GEN-LAST:event_rbnStudentActionPerformed

    private void rbnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbnAdminActionPerformed
       
    }//GEN-LAST:event_rbnAdminActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        if(rbnAdmin.isSelected()){
            //To check whther the admin is registered or not.
           String username = txtUsername.getText();
           String password = String.valueOf(txtPassword.getPassword());
           String empty = "";
           
           //For validating
           if(username.equals(empty)){
               JOptionPane.showMessageDialog(this, "Please Provide Your Username");
           }
           else if(password.equals(empty)){
               JOptionPane.showMessageDialog(this, "Please Provide Your Password");
           }
           else{
               try {
                   databaseNibriti db=new databaseNibriti();
                   ResultSet result=db.adminlogin(username,password);
                   if(result.next())
                   {
                       JOptionPane.showMessageDialog(null,"Login Successfull"); 
                       //To display admin dashboard
                       AdminDash ad= new AdminDash();
                       ad.setVisible(true);
                       this.dispose();
                       ad.setResizable(false);
                   }
                   else
                   {
                       JOptionPane.showMessageDialog(null,"Unable to login");
                   }
            }

            catch (Exception ex) {
            }
           }
         }
        
        else if(rbnStudent.isSelected()){
            //To check whether the student is registered or not.
            String token = txtUsername.getText();
            String studentpw = String.valueOf(txtPassword.getPassword());
            String empty = "";

            //For validating
            if(token.equals(empty)){
                JOptionPane.showMessageDialog(this, "Token ID is empty! Please re-enter...");
            }
            else if(studentpw.equals(empty)){
                JOptionPane.showMessageDialog(this, "Password is empty! Please re-enter...");
            }
            else{
                try {
                    databaseNibriti db=new databaseNibriti();
                    
                    ResultSet eresult=db.studentlogin(token,studentpw);
                    if(eresult.next())
                    {
                        JOptionPane.showMessageDialog(null,"Login Successfull");
                        
                        //To retieve the name of the student using his/her tokenid
                        String query = "Select studentname from student Where token_id='"+token+"'";
                        PreparedStatement stmt = db.conn.prepareStatement(query);
                        ResultSet rs=stmt.executeQuery();
                         while(rs.next()){
                            uname=(rs.getString("studentname"));
                    
                            }
                        System.out.println(uname);
                        
                        //To diplay Student dashboard with the associated student name
                        StudentDash studentdash= new StudentDash(uname);
                        studentdash.setVisible(true);
                        this.dispose();
                        studentdash.setResizable(false);

                    }
                    else
                    {
                        JOptionPane.showMessageDialog(null,"Unable to login");
                    }            
             }

             catch (Exception ex) {

             }

            }
            }
    }//GEN-LAST:event_btnLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JRadioButton rbnAdmin;
    private javax.swing.JRadioButton rbnStudent;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
